version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8 # Use Amazon Corretto 8 for better support with AWS environments
    commands:
      - echo "Installing additional dependencies if needed"
      - apt-get update -y
      - apt-get install -y zip # Ensure `zip` is available for creating artifacts
  pre_build:
    commands:
      - echo "Listing environment information"
      - which mvn || echo "Maven not found!"
      - mvn -version || echo "Maven version unavailable!"
      - pwd
      - ls -al # Debugging step to verify directory contents
  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Creating tarball for deployment"
      - mkdir -p appfiles
      - cp target/HelloWorld-1.war appfiles/ # Ensure the WAR file is copied correctly
      - cp appspec.yml appfiles/
      - cd appfiles
      - tar -zcvf ../target/HelloWorld.tar.gz *.*
      - cd ..
      - echo "Tarball created successfully"
artifacts:
  files:
    - target/HelloWorld.tar.gz
  discard-paths: yes
